/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * SMA.Api
 * OpenAPI spec version: 1.0
 */
export interface Vehicle {
  createdOn?: string;
  id?: number;
  schoolId?: number;
  seatingCapacity?: number;
  /** @nullable */
  vehicleNumber?: string | null;
  /** @nullable */
  vehicleType?: string | null;
}

export interface VehicleResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  value?: Vehicle;
}

export interface VehicleIEnumerableResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  /** @nullable */
  readonly value?: readonly Vehicle[] | null;
}

export interface UserModel {
  /** @nullable */
  password?: string | null;
  /** @nullable */
  username?: string | null;
}

export interface Subject {
  createdOn?: string;
  id?: number;
  schoolId?: number;
  /** @nullable */
  subjectName?: string | null;
}

export interface SubjectResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  value?: Subject;
}

export interface SubjectIEnumerableResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  /** @nullable */
  readonly value?: readonly Subject[] | null;
}

export interface Student {
  /** @nullable */
  aadhaarNumber?: string | null;
  /** @nullable */
  admissionNumber?: string | null;
  createdOn?: string;
  dateOfBirth?: string;
  fatherId?: number;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  gender?: string | null;
  guardianId?: number;
  id?: number;
  /** @nullable */
  lastName?: string | null;
  motherId?: number;
  /** @nullable */
  photo?: string | null;
  primaryId?: number;
  schoolId?: number;
}

export interface StudentResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  value?: Student;
}

export interface StudentIEnumerableResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  /** @nullable */
  readonly value?: readonly Student[] | null;
}

export interface StringResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  /** @nullable */
  readonly value?: string | null;
}

export interface Staff {
  /** @nullable */
  aadhaarNumber?: string | null;
  createdOn?: string;
  dateOfBirth?: string;
  dateOfJoin?: string;
  departmentId?: number;
  /** @nullable */
  emailId?: string | null;
  experiance?: number;
  /** @nullable */
  firstName?: string | null;
  id?: number;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  permanentAddress?: string | null;
  /** @nullable */
  photo?: string | null;
  /** @nullable */
  primaryPhone?: string | null;
  /** @nullable */
  qualification?: string | null;
  schoolId?: number;
  /** @nullable */
  secondaryPhone?: string | null;
  /** @nullable */
  temporaryAddress?: string | null;
}

export interface StaffResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  value?: Staff;
}

export interface StaffIEnumerableResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  /** @nullable */
  readonly value?: readonly Staff[] | null;
}

export interface Section {
  createdOn?: string;
  id?: number;
  schoolId?: number;
  /** @nullable */
  sectionName?: string | null;
}

export interface SectionResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  value?: Section;
}

export interface SectionIEnumerableResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  /** @nullable */
  readonly value?: readonly Section[] | null;
}

export interface SchoolResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  value?: School;
}

export interface SchoolIEnumerableResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  /** @nullable */
  readonly value?: readonly School[] | null;
}

export interface SchoolDetail {
  createdOn?: string;
  /** @nullable */
  emailId?: string | null;
  id?: number;
  /** @nullable */
  phoneNumber?: string | null;
  schoolId?: number;
  /** @nullable */
  socialMediaId?: string | null;
  /** @nullable */
  socialMediaType?: string | null;
}

export interface SchoolDetailResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  value?: SchoolDetail;
}

export interface SchoolDetailIEnumerableResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  /** @nullable */
  readonly value?: readonly SchoolDetail[] | null;
}

export interface School {
  accreditationStatus?: boolean;
  /** @nullable */
  boardType?: string | null;
  /** @nullable */
  branchName?: string | null;
  createdOn?: string;
  /** @nullable */
  establishedYear?: string | null;
  id?: number;
  /** @nullable */
  registrationNumber?: string | null;
  /** @nullable */
  schoolAddress?: string | null;
  /** @nullable */
  schoolName?: string | null;
}

export interface RouteStop {
  createdOn?: string;
  id?: number;
  routeId?: number;
  schoolId?: number;
  /** @nullable */
  stopName?: string | null;
}

export interface RouteStopResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  value?: RouteStop;
}

export interface Route {
  createdOn?: string;
  /** @nullable */
  endingPoint?: string | null;
  id?: number;
  /** @nullable */
  routeName?: string | null;
  routeNumber?: number;
  schoolId?: number;
  /** @nullable */
  startingPoint?: string | null;
}

export interface RouteResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  value?: Route;
}

export interface RouteIEnumerableResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  /** @nullable */
  readonly value?: readonly Route[] | null;
}

export interface Role {
  createdOn?: string;
  id?: number;
  /** @nullable */
  roleName?: string | null;
  schoolId?: number;
}

export interface RoleResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  value?: Role;
}

export interface RoleIEnumerableResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  /** @nullable */
  readonly value?: readonly Role[] | null;
}

export interface Result {
  error?: Error;
  readonly isSuccess?: boolean;
}

export interface Parent {
  /** @nullable */
  aadhaarNumber?: string | null;
  createdOn?: string;
  /** @nullable */
  emailId?: string | null;
  /** @nullable */
  firstName?: string | null;
  id?: number;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  occupation?: string | null;
  /** @nullable */
  parentType?: string | null;
  /** @nullable */
  permanentAddress?: string | null;
  /** @nullable */
  photo?: string | null;
  /** @nullable */
  primaryPhone?: string | null;
  schoolId?: number;
  /** @nullable */
  secondaryPhone?: string | null;
  /** @nullable */
  temporaryAddress?: string | null;
}

export interface ParentResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  value?: Parent;
}

export interface ParentIEnumerableResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  /** @nullable */
  readonly value?: readonly Parent[] | null;
}

export interface Notification {
  createdOn?: string;
  id?: number;
  /** @nullable */
  notificationType?: string | null;
  recipientId?: number;
  schoolId?: number;
  senderId?: number;
  sentDate?: string;
  status?: boolean;
  /** @nullable */
  title?: string | null;
}

export interface MessageType {
  createdOn?: string;
  id?: number;
  /** @nullable */
  messageTypeName?: string | null;
  schoolId?: number;
}

export interface MessageTemplate {
  /** @nullable */
  body?: string | null;
  createdOn?: string;
  id?: number;
  /** @nullable */
  messageTemplateName?: string | null;
  schoolId?: number;
}

export interface FilterModel {
  pageIndex?: number;
  pageSize?: number;
  /** @nullable */
  search?: string | null;
  /** @nullable */
  sortColumn?: string | null;
  /** @nullable */
  sortDirection?: string | null;
}

export interface ExamType {
  createdOn?: string;
  /** @nullable */
  examTypeName?: string | null;
  id?: number;
  schoolId?: number;
}

export interface Error {
  /** @nullable */
  code?: string | null;
  /** @nullable */
  message?: string | null;
}

export interface RouteStopIEnumerableResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  /** @nullable */
  readonly value?: readonly RouteStop[] | null;
}

export interface NotificationResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  value?: Notification;
}

export interface NotificationIEnumerableResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  /** @nullable */
  readonly value?: readonly Notification[] | null;
}

export interface MessageTypeResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  value?: MessageType;
}

export interface MessageTypeIEnumerableResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  /** @nullable */
  readonly value?: readonly MessageType[] | null;
}

export interface MessageTemplateResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  value?: MessageTemplate;
}

export interface MessageTemplateIEnumerableResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  /** @nullable */
  readonly value?: readonly MessageTemplate[] | null;
}

export interface ExamTypeResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  value?: ExamType;
}

export interface ExamTypeIEnumerableResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  /** @nullable */
  readonly value?: readonly ExamType[] | null;
}

export interface Department {
  createdOn?: string;
  /** @nullable */
  departmentName?: string | null;
  id?: number;
  schoolId?: number;
}

export interface DepartmentResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  value?: Department;
}

export interface DepartmentIEnumerableResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  /** @nullable */
  readonly value?: readonly Department[] | null;
}

export interface DbConnectionModel {
  /** @nullable */
  dbName?: string | null;
  /** @nullable */
  environment?: string | null;
  integratedSecurity?: boolean;
  /** @nullable */
  key?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  server?: string | null;
  /** @nullable */
  userId?: string | null;
}

export interface DbConnectionModelIListResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  /** @nullable */
  readonly value?: readonly DbConnectionModel[] | null;
}

export interface Class {
  /**
   * @minLength 1
   * @pattern ^[a-zA-Z0-9\s\-.,'#&()]+$
   */
  className: string;
  createdOn?: string;
  id?: number;
  schoolId?: number;
}

export interface ClassResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  value?: Class;
}

export interface ClassIEnumerableResult {
  error?: Error;
  readonly isSuccess?: boolean;
  totalCount?: number;
  /** @nullable */
  readonly value?: readonly Class[] | null;
}

